name: Instagram Data Collector

on:
  schedule:
    - cron: '0 22 * * *'  # 매일 오전 7시 (KST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client requests

      - name: Write credentials.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > credentials.json

      - name: Run script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python main.py
